// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liacqzbvezvpmluasbld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpYWNxemJ2ZXp2cG1sdWFzYmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjYxNTYsImV4cCI6MjA2MjY0MjE1Nn0.4aR0NiaOJbMYrOWe5_W823hNMOGe3zS3UkBuxgm8U8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});